export const CAR_DETAIL_NAME = {
  title: 'Naziv',
  brand: 'Marka',
  model: 'Model',
  volume: 'Zapremina motora',
  price: 'Cijena (€)',
  year: 'Godina proizvodnje',
  mileage: 'Kilometraža (km)',
  engineType: 'Vrsta motora',
  transmission: 'Vrsta mjenjača',
  enginePower: 'Snaga motora (kw)',
  chassisNumber: 'Broj šasije',
  oldPrice: 'Stara cijena (€)',
  isIncoming: 'U dolasku ⏱️',
}
